<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DesktopPet.Application/DesktopPet.Application.csproj" />
    <ProjectReference Include="../../src/DesktopPet.Infrastructure/DesktopPet.Infrastructure.csproj" />
    <ProjectReference Include="../../src/DesktopPet.AI/DesktopPet.AI.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
